version: '3.9'
services:

  mosquitto:
    container_name: mosquitto
    build: ./mosquitto/
    restart: unless-stopped
    environment:
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - '1883:1883'
      - '9001:9001'

  telegraf:
    container_name: telegraf
    image: telegraf:1.19.3
    restart: unless-stopped
    environment:
      MOSQUITTO_USERNAME: ${MOSQUITTO_USERNAME}
      MOSQUITTO_PASSWORD: ${MOSQUITTO_PASSWORD}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - '8125:8125'

  influxdb:
    container_name: influxdb
    image: influxdb:2.0
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: goats
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: goats
      DOCKER_INFLUXDB_INIT_BUCKET: sensor-measurements
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    ports:
      - '8086:8086'

  web:
    network_mode: "host"
    container_name: nginx
    image: nginx:1.21.5
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    # ports:
    #   - '80:80'
    #   - '81:81'
    #   - '443:443'

  # nginx-proxy-manager:
  #   network_mode: "host"
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - nginx-proxy-manager-data:/data
  #     - nginx-proxy-manager-letsencrypt:/etc/letsencrypt

volumes:
  mosquitto:
  telegraf:
  influxdb-data:
  influxdb-config:
  # nginx-proxy-manager-data:
  # nginx-proxy-manager-letsencrypt:
