version: '3.9'
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '1883:1883'
      - '9001:9001'

  telegraf:
    container_name: telegraf
    image: telegraf:1.19.3
    restart: always
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - '8125:8125'

  influxdb:
    container_name: influxdb
    image: influxdb:2.0
    restart: always
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=set up
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    ports:
      - '8086:8086'

volumes:
  mosquitto:
  telegraf:
  influxdb_data:
  influxdb_config:
